addr/urls.py
from django.urls import path

from .views import addr_data, addr_list


urlpatterns = [
    path("", addr_data, name="index"),
    path("result/", addr_list, name="result"),
]

company/urls.py
from django.urls import path

from .views import (company_data,
                    company_list)


urlpatterns = [
    path("", company_data, name="index"),
    path("result/", company_list, name="result"),
]

employee/urls.py
from django.urls import path

from .views import (
    employee_data,
    employee_list)


urlpatterns = [
    path("", employee_data, name="index"),
    path("result/", employee_list, name="result"),
]

euroemp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("address/", include("addr.urls")),
    path("company/", include("company.urls")),
    path("employee/", include("employee.urls")),

]

addr/models.py
from django.db import models


class Country_List(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=50)
    population = models.CharField(max_length=15)
    area_km2 = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Addr_Info(models.Model):
    address_line1 = models.CharField(max_length=250)
    number = models.IntegerField(blank=True)
    others = models.CharField(max_length=150, blank=True)
    city = models.CharField(max_length=150)
    county = models.CharField(max_length=150)
    country = models.ForeignKey(Country_List, on_delete=models.SET_NULL, null=True)
    zip_code = models.CharField(max_length=10)

    def __str__(self):
        return (self.address_line1 + ' - ' + str(self.number) + ' ' + self.others + ' --> '
                + self.city + ' - ' + self.county )

company/models.py
from django.db import models
from addr.models import Addr_Info


class Comp_Info(models.Model):
    identify = models.CharField(unique=True, max_length=50)
    name = models.CharField(max_length=200)
    url = models.URLField(max_length=255, blank=True)
    contact = models.CharField(max_length=150)
    activity = models.CharField(max_length=250)
    address = models.ForeignKey("addr.Addr_Info", on_delete=models.CASCADE)

    def __str__(self):
        return (self.identify + ' - ' + self.name)

employee/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, EmailValidator
from addr.models import Addr_Info
from company.models import Comp_Info


class Employee_Info(models.Model):
    company_number = models.IntegerField(primary_key=True, unique=True, validators=[MinValueValidator(1), MaxValueValidator(500)])
    start_date = models.DateField()
    prefix = models.CharField(max_length=4, blank=True)
    name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=250, blank=True)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField(blank=True)
    mobile_phone = models.CharField(max_length=15, blank=True)
    email = models.CharField(max_length=150, validators=[EmailValidator()])
    area_of_work = models.CharField(max_length=150, blank=True)
    disabled = models.BooleanField(blank=True)
    address = models.ForeignKey("addr.Addr_Info", on_delete=models.CASCADE)
    company = models.ForeignKey("company.Comp_Info", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.company_number) + ' - ' + self.name + ' ' + self.last_name + ' --> ' + self.email

addr/forms.py
from django import forms
from django.core import validators

from .models import Addr_Info, Country_List


class Addr_Form(forms.ModelForm):
    def clean(self):
        clean_data = super(Addr_Form, self).clean()

    zip_code = forms.CharField(validators=[validators.RegexValidator('^(^[0-9]{4}(?:-[0-9]{3})?$|^$)')])

    class Meta:
        model = Addr_Info
        fields = [
            'address_line1',
            'number',
            'others',
            'city',
            'county',
            'country',
            'zip_code'
        ]

company/forms.py
from django import forms
from django.core import validators

from .models import Comp_Info


class Company_Form(forms.ModelForm):
    def clean(self):
        clean_data = super(Company_Form, self).clean()

    url = forms.CharField(validators=[validators.URLValidator(message='This url is not valid.')])

    class Meta:
        model = Comp_Info
        fields = [
            'identify',
            'name',
            'url',
            'contact',
            'activity',
            'address'
        ]

employee/forms.py
from django import forms
from django.core import validators

from .models import Employee_Info


class Employee_Form(forms.ModelForm):
    def clean(self):
        clean_data = super(Employee_Form, self).clean()

    company_number = forms.IntegerField(validators=[validators.MinValueValidator(1),
                                                    validators.MaxValueValidator(500)])

    class Meta:
        model = Employee_Info
        fields = [
            'company_number',
            'start_date',
            'prefix',
            'name',
            'middle_name',
            'last_name',
            'date_of_birth',
            'mobile_phone',
            'email',
            'area_of_work',
            'address',
            'company',
            'disabled',
        ]

addr/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from .forms import Addr_Form
from .models import Addr_Info


def addr_data(request):
    address = Addr_Form()

    if request.method == 'POST':
        address = Addr_Form(request.POST or None)
        if address.is_valid():
            address.full_clean()
            address.save()
            return HttpResponseRedirect(reverse_lazy(addr_list))
        else:
            return render(request, 'addr/addr.html', {'form': address})

    return render(request, 'addr/addr.html', {'form': address})

def addr_list(request):
    addr = Addr_Info.objects.all()
    return render(request, "addr/registered.html", {"address": addr})

def success(request):
    return render(request, 'addr/registered.html', {})

company/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from .forms import Company_Form
from .models import Comp_Info


def company_data(request):
    company = Company_Form()

    if request.method == 'POST':
        company = Company_Form(request.POST or None)
        if company.is_valid():
            company.full_clean()
            company.save()
            return HttpResponseRedirect(reverse_lazy(company_list))
        else:
            return render(request, 'company/company.html', {'form': company})

    return render(request, 'company/company.html', {'form': company})

def company_list(request):
    company = Comp_Info.objects.all()
    return render(request, "company/registered.html", {"company": company})

employee/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from .forms import Employee_Form
from .models import Employee_Info


def employee_data(request):
    emp = Employee_Form()

    if request.method == 'POST':
        emp = Employee_Form(request.POST or None)
        if emp.is_valid():
            emp.full_clean()
            emp.save()
            return HttpResponseRedirect(reverse_lazy(employee_list))
        else:
            return render(request, 'employee/employee.html', {'form': emp})

    return render(request, 'employee/employee.html', {'form': emp})

def employee_list(request):
    emp = Employee_Info.objects.all()
    return render(request, "employee/results.html", {"employee": emp})


def success(request):
    return render(request, 'employee/registered.html', {})

addr/templates/addr/addr.html
{% load static %}
<link rel="stylesheet" href="{% static 'employee/style.css' %}">

{% block center %}
<head>
    <title>
        Address
    </title>
</head>
<body>
<div class="bs-square" role="main">
    <h1 class="panel-title">Address Creation Page</h1>
    <form class="form-inline" action="" role="form" method="post">
        {% csrf_token %}
        <section aria-label="Local" class="form-group">
            <label class="control-label area">Street name:<br/>
                {{ form.address_line1 }}
                <font color="red">{{ form.errors.address_line1 }}</font><br/>
            </label>
            <label class="control-label area">Number:<br/>
                {{ form.number }}
                <font color="red">{{ form.errors.number }}</font><br/>
            </label>
            </span>
            <label class="control-label area">More Address Information:<br/>
                {{ form.others }}
                <font color="red">{{ form.errors.others }}</font><br/>
            </label>
        </section>
        <section aria-label="Regional" class="form-group">
            <label class="control-label area">City:<br/>
                {{ form.city }}
                <font color="red">{{ form.errors.city }}</font><br/>
            </label>
            <label class="control-label area">County or State:<br/>
                {{ form.county }}
                <font color="red">{{ form.errors.county }}</font><br/>
            </label>
            <label class="control-label area">Country:</label><br/>
            {{ form.country }}
            <font color="red">{{ form.errors.country }}</font><br/>
            <label class="control-label area">Zip Code:<br/>
                {{ form.zip_code }}
                <font color="red">{{ form.errors.zip_code }}</font><br/>
            </label>
        </section>
        <button type="submit" class="submit">Submit</button>
    </form>
</div>
</body>
<script>
    var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Add the street name...';
		form_fields[1].style='width:500px;';
		form_fields[2].placeholder='Add the number...';
		form_fields[2].style='width:130px;';
		form_fields[3].placeholder='Other Address Information...';
		form_fields[3].style='width:500px;';
		form_fields[4].placeholder='Add the name of the city...';
		form_fields[4].style='width:400px;';
		form_fields[5].placeholder='Add the name of the county/state...';
		form_fields[5].style='width:400px;';
		form_fields[6].placeholder='Add the zip code...';
		form_fields[6].style='width:130px;';

    for (var field in form_fields) {
        form_fields[field].className += 'form-control area';
	}
    document.getElementById('id_country').className += 'form-control area';
    //TODO: Remove the comments below to fix some tests.
    // document.documentElement.setAttribute('lang', navigator.language);
    // document.getElementById('id_country').setAttribute('aria-label', 'Country');
    var collection = document.getElementsByTagName('form');
    //TODO: Remove the lines below to fix some tests.
    document.getElementById('id_others').setAttribute('tabindex', 1);
    document.getElementById('id_county').setAttribute('tabindex', 2);
</script>
{% endblock %}

addr/templates/addr/registered.html
{% load static %}
<link rel="stylesheet" href="{% static 'addr/style.css' %}">

{% block center %}
<title>
    Address
</title>
{% for addr in address.all %}
    {% if forloop.last %}
        <h1>{{ addr }} </br>had been added with success!</h1>
    {% endif %}
{% endfor %}
<ul>
{% for addr in address.all %}
    <li>{{addr.address_line1}} - {{addr.number}}, {{ addr.others }}; City: {{ addr.city }} - County: {{ addr.county }} - Country: {{addr.country.name}}</li>
{% endfor %}
</ul>
{% endblock %}

company/templates/company/company.html
{% load static %}
<link rel="stylesheet" href="{% static 'company/style.css' %}" xmlns="http://www.w3.org/1999/html">

{% block center %}

<div class="bs-square">
    <h1 class="panel-title">Address Creation Page</h1>
    <form class="form-inline" action="" role="form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="area">
                <div class="identify">
                    {{ form.identify.label }}<br/>
                    {{ form.identify }}
                    <font color="red">{{ form.error.identify }}</font><br/>
                </div>
            </div>
            <div class="area">
                <div class="name">
                    {{ form.name.label }}<br/>
                    {{ form.name }}
                    <font color="red">{{ form.error.name }}</font><br/>
                </div>
            </div>

            <div class="area">
                {{ form.url.label}}<br/>
                {{ form.url }}
                <font color="red">{{ form.error.url }}</font><br/>
            </div>

            <div class="area">
                {{ form.contact.label }}<br/>
                {{ form.contact }}
                <font color="red">{{ form.error.contact }}</font><br/>
            </div>

            <div class="area">
                {{ form.activity.label }}<br/>
                {{ form.activity }}
                <font color="red">{{ form.error.activity }}</font><br/>
            </div>
        </div>
        <div class="form-group">
            <div class="area">
                {{ form.address.label }}<br/>
                {{ form.address }}
                <font color="red">{{ form.error.address }}</font><br/>
            </div>
        </div>
        <button type="submit" class="submit">Submit</button>
    </form>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Add the Unique Identify...';
		form_fields[1].style='width:150px;';
		form_fields[2].placeholder='Add the company nname...';
		form_fields[2].style='width:250px;';
		form_fields[3].placeholder='Add the company URL...';
		form_fields[3].style='width:250px;';
		form_fields[4].placeholder='Add the contact of the responsable';
		form_fields[4].style='width:250px;';
		form_fields[5].placeholder='Add the company activity...';
		form_fields[5].style='width:250px;';
    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
	}
</script>

{% endblock %}

company/templates/company/registered.html
{% load static %}
<link rel="stylesheet" href="{% static 'company/style.css' %}">

{% block center %}
<div class="bs-success">
    <h1> Company was registered with success! </h1>

</div>
<div>
    <a class="back" href="{{request.META.HTTP_REFERER|escape}}">Go back</a>
</div>
{% endblock %}

employee/templates/employee/employee.html
{% load static %}
<link rel="stylesheet" href="{% static 'employee/style.css' %}">

{% block center %}
<div class="bs-square">
    <h1> Employee Registration </h1>
    <form class="form-inline" action="" role="form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <h3>Company Data</h3>
            <div class="area">
                <label for="id_company_number">Employee number</label><br/>
                {{ form.company_number }}
                <font color="red">{{ form.error.company_number }}</font><br/>
            </div>
            <div class="area">
                {{ form.start_date.label }}<br/>
                {{ form.start_date }}
                <font color="red">{{ form.error.start_date }}</font><br/>
            </div>
            <div class="area">
                {{ form.area_of_work.label }}<br/>
                {{ form.area_of_work }}
            </div>
        </div>
        <div class="form-group">
            <h3>Employee Data</h3>
            <div class="area">
                {{ form.prefix.label }} <br/>
                {{ form.prefix }}
            </div>
            <div class="area">
                {{ form.name.label }} <br/>
                {{ form.name }}
                <font color="red">{{ form.error.name }}</font><br/>
            </div>
            <div class="area">
                {{ form.middle_name.label }}<br/>
                {{ form.middle_name }}
            </div>
            <div class="area">
                {{ form.last_name.label }}<br/>
                {{ form.last_name }}
                <font color="red">{{ form.error.last_name }}</font><br/>
            </div>
            <div class="area">
                {{ form.date_of_birth.label }}<br/>
                {{ form.date_of_birth }}
                <font color="red">{{ form.error.date_of_birth }}</font><br/>
            </div>
            <div class="area">
                {{ form.mobile_phone.label }}<br/>
                {{ form.mobile_phone }}
                <font color="red">{{ form.error.mobile_phone }}</font><br/>
            </div>
            <div class="area">
                {{ form.email.label }}<br/>
                {{ form.email }}
                <font color="red">{{ form.error.email }}</font><br/>
            </div>
        </div>

        <div class="form-group">
            <div class="area">
                {{ form.address.label }}<br/>
                {{ form.address }}
                <font color="red">{{ form.error.address }}</font><br/>
            </div>

            <div class="area">
                {{ form.company.label }}<br/>
                {{ form.company }}
                <font color="red">{{ form.error.company }}</font><br/>
            </div>
        </div>

        <div class="area">
            {{ form.disabled.label }}
            {{ form.disabled }}
        </div>

        <button type="submit" class="submit">Submit</button>

</form>
</div>

<script>
    var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Add Number...';
		form_fields[1].style='width:110px;';
		form_fields[2].type='date';
		form_fields[3].placeholder='Insert the Employee area in the Company...';
		form_fields[3].style='width:500px;';
		form_fields[4].style='width:55px;';
		form_fields[5].placeholder='Insert the Employee First Name...';
		form_fields[5].style='width:500px;';
		form_fields[6].placeholder='Insert the Employee Middle Name...';
		form_fields[6].style='width:500px;';
		form_fields[7].placeholder='Insert the Employee Last Name...';
		form_fields[7].style='width:500px;';
		form_fields[8].type='date';
		form_fields[9].placeholder='Add Phone Number...';
		form_fields[9].type='tel';
		form_fields[9].style='width:150px;';
		form_fields[10].placeholder='Add Email...';
		form_fields[10].type='email';
		form_fields[10].style='width:500px;';

    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
	}

    var prefixInput = form_fields[4]
	var prefixSelect = document.createElement('select');

    var currentValue = prefixInput.value || prefixSelect.getAttribute('value');

    var options = [{value: '', text: '--'},
                   {value: 'Mr', text: 'Mr.'},
                   {value: 'Mrs', text: 'Mrs.'},
                   {value: 'Ms', text: 'Ms.'},
                   {value: 'Miss', text: 'Miss'},
                   {value: 'Prof', text: 'Prof.'},
                   {value: 'Dr', text: 'Dr.'},
                   {value: 'Eng', text: 'Eng.'},
                   ];
    options.forEach(function (option, i) {
        var optionElement = document.createElement('option');
        optionElement.appendChild(document.createTextNode(option.text));
        optionElement.setAttribute('value', option.value);
        prefixSelect.appendChild(optionElement);

        // if the option matches the existing input's value, select it
        if (option.value == currentValue) {
            prefixSelect.selectedIndex = i;
        }
    });
    for (var i = 0; i < prefixInput.attributes.length; ++ i) {
    var attribute = prefixInput.attributes[i];

    // type and value don't apply, so skip them
    // ** you might also want to skip style, or others -- modify as needed **
    if (attribute.name != 'type' && attribute.name != 'value') {
        prefixSelect.setAttribute(attribute.name, attribute.value);
    }
}

    // finally, replace the old input element with the new select element
    prefixInput.parentElement.replaceChild(prefixSelect, prefixInput);
</script>
{% endblock %}

employee/templates/employee/registered.html
{% load static %}
<link rel="stylesheet" href="{% static 'employee/style.css' %}">

{% block center %}
<div class="bs-success">
    <h1> Employee was registered with success! </h1>

</div>
<div>
    <a class="back" href="{{request.META.HTTP_REFERER|escape}}">Go back</a>
</div>
{% endblock %}

employee/templates/employee/results.html
{% load static %}
<link rel="stylesheet" href="{% static 'employee/style.css' %}">

{% block center %}
{% for emp in employee.all %}
    {% if forloop.last %}
        <h1>{{ emp.name }} had been added with success!</h1>
    {% endif %}
{% endfor %}


<ul>
{% for emp in employee.all %}
    <li>{{emp.company_number}}: {{emp.prefix}}. {{ emp.name }} {{ emp.last_name }} --> {{ emp.area_of_work }}</li>
{% endfor %}
</ul>
{% endblock %}